import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } })
const errors = []
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message))
await page.goto('file://' + process.cwd() + '/dist/index.html')
await page.waitForTimeout(2500)
await page.evaluate(() => { window.__ft.getState().login('colebucket06@gmail.com', 'Pathways!Admin#2026Cc'); window.__ft.getState().launchApp() })
await page.waitForTimeout(700)
await page.locator('.nav-tab', { hasText: 'Test Management' }).click()
await page.waitForTimeout(600)
const detailW1 = await page.evaluate(() => Math.round(document.querySelector('.col.detail').getBoundingClientRect().width))
const btns = page.locator('.col-head button[title*="Collapse this panel"]')
console.log('visible collapse handles:', await btns.count())
await btns.nth(0).click(); await page.waitForTimeout(300)
await page.locator('.col-head button[title*="Collapse this panel"]').first().click(); await page.waitForTimeout(300)
const rails = await page.locator('.col.collapsed').count()
const railText = await page.locator('.rail-tag .rail-text').allTextContents()
const detailW2 = await page.evaluate(() => Math.round(document.querySelector('.col.detail').getBoundingClientRect().width))
console.log('rails:', rails, railText, '| detail width:', detailW1, '→', detailW2)
await page.screenshot({ path: 'shot-collapsed.png' })
await page.locator('.col.collapsed').first().click(); await page.waitForTimeout(300)
console.log('rail re-expands (expect 1 left):', await page.locator('.col.collapsed').count())

// log read/clear
await page.locator('.txn-banner').click(); await page.waitForTimeout(400)
console.log('unread filter with count:', (await page.locator('.log-panel button', { hasText: 'unread' }).textContent()))
await page.locator('.log-panel button', { hasText: '✓ Mark all read' }).click(); await page.waitForTimeout(300)
console.log('unread after mark:', await page.evaluate(() => window.__ft.getState().changeLog.filter((e) => !e.read).length))
await page.locator('.log-panel button', { hasText: '🗑 Clear log' }).click(); await page.waitForTimeout(200)
await page.locator('.log-panel button', { hasText: '✓ Confirm clear' }).click(); await page.waitForTimeout(300)
console.log('after clear:', await page.evaluate(() => { const l = window.__ft.getState().changeLog; return l.length + ' — ' + l[0]?.summary.slice(0, 35) }))
console.log(errors.length ? 'ERRORS:\n' + errors.slice(0, 5).join('\n') : 'ALL OK')
await browser.close()
