import * as XLSX from 'xlsx'

const download = (blob, filename) => {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(a.href), 5000)
}

const caseRows = (tc) => {
  const rows = []
  tc.executions.forEach((x) => {
    x.stepResults.forEach((sr, i) => {
      const step = tc.steps.find((s) => s.id === sr.stepId)
      rows.push({
        'Test Case': tc.name,
        'Executed At': new Date(x.executedAt).toLocaleString(),
        'Executed By': x.executedBy,
        'Overall Status': x.overallStatus,
        'Execution State': x.state,
        'Step #': i + 1,
        'Action': step?.action || '',
        'Expected': step?.expected || '',
        'Step Status': sr.status,
        'Actual Result': sr.actual || '',
        'Comment': i === 0 ? x.comment || '' : '',
      })
    })
    if (!x.stepResults.length) rows.push({ 'Test Case': tc.name, 'Executed At': new Date(x.executedAt).toLocaleString(), 'Executed By': x.executedBy, 'Overall Status': x.overallStatus, 'Execution State': x.state, 'Comment': x.comment || '' })
  })
  return rows
}

export const exportJSON = (tc) =>
  download(new Blob([JSON.stringify(tc, null, 2)], { type: 'application/json' }), `${tc.name.replace(/\W+/g, '_')}.json`)

export const exportCSV = (tc) => {
  const ws = XLSX.utils.json_to_sheet(caseRows(tc))
  download(new Blob([XLSX.utils.sheet_to_csv(ws)], { type: 'text/csv' }), `${tc.name.replace(/\W+/g, '_')}.csv`)
}

export const exportXLSX = (tc) => {
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet([{ Name: tc.name, Objective: tc.objective, Preconditions: tc.preconditions, Steps: tc.steps.length, Executions: tc.executions.length }]), 'Summary')
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(tc.steps.map((s, i) => ({ '#': i + 1, Action: s.action, 'Expected Result': s.expected }))), 'Steps')
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(caseRows(tc)), 'Executions')
  const out = XLSX.write(wb, { type: 'array', bookType: 'xlsx' })
  download(new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), `${tc.name.replace(/\W+/g, '_')}.xlsx`)
}

const reportHTML = (tc) => `<!doctype html><html><head><meta charset="utf-8"><title>${tc.name} — Test Report</title>
<style>body{font-family:Segoe UI,Arial,sans-serif;margin:36px;color:#111}h1{border-bottom:3px solid #4f7cff;padding-bottom:8px}
table{border-collapse:collapse;width:100%;margin:12px 0}th,td{border:1px solid #bbb;padding:6px 9px;font-size:13px;text-align:left}
th{background:#eef2ff}.Pass{color:#15803d;font-weight:700}.Fail{color:#b91c1c;font-weight:700}</style></head><body>
<h1>${tc.name}</h1>
<p><b>Objective:</b> ${tc.objective || '—'}<br/><b>Preconditions:</b> ${tc.preconditions || '—'}</p>
<h2>Test Steps</h2><table><tr><th>#</th><th>Action</th><th>Expected Result</th></tr>
${tc.steps.map((s, i) => `<tr><td>${i + 1}</td><td>${s.action}</td><td>${s.expected}</td></tr>`).join('')}</table>
<h2>Execution History</h2><table><tr><th>Date</th><th>By</th><th>Status</th><th>State</th><th>Comment</th></tr>
${tc.executions.map((x) => `<tr><td>${new Date(x.executedAt).toLocaleString()}</td><td>${x.executedBy}</td><td class="${x.overallStatus.replace(/\s/g, '')}">${x.overallStatus}</td><td>${x.state}</td><td>${x.comment || ''}</td></tr>`).join('')}</table>
<p style="margin-top:30px;color:#777;font-size:11px">Generated by Pathways.io — ${new Date().toLocaleString()}</p></body></html>`

export const exportPDF = (tc) => {
  const w = window.open('', '_blank')
  if (!w) return alert('Popup blocked — allow popups to export PDF.')
  w.document.write(reportHTML(tc))
  w.document.close()
  setTimeout(() => w.print(), 350)
}

export const exportWord = (tc) =>
  download(new Blob(['﻿' + reportHTML(tc)], { type: 'application/msword' }), `${tc.name.replace(/\W+/g, '_')}.doc`)

export const exportProjectFile = (obj, name) =>
  download(new Blob([JSON.stringify(obj, null, 2)], { type: 'application/json' }), `${(name || 'project').replace(/\W+/g, '_')}.flowtest.json`)

// ---------- input templates (round-trip with the Import Wizard) ----------
const TEMPLATE_ROWS = [
  { 'Suite': 'Checkout Regression', 'Title': 'Login with valid credentials', 'Objective': 'Verify a registered user can sign in', 'Preconditions': 'User account exists', 'Step Action': '', 'Step Expected': '' },
  { 'Suite': '', 'Title': '', 'Objective': '', 'Preconditions': '', 'Step Action': 'Navigate to login page', 'Step Expected': 'Login form is displayed' },
  { 'Suite': '', 'Title': '', 'Objective': '', 'Preconditions': '', 'Step Action': 'Enter valid credentials and submit', 'Step Expected': 'User lands on dashboard' },
  { 'Suite': 'Checkout Regression', 'Title': 'Password reset flow', 'Objective': 'Verify reset email is sent', 'Preconditions': 'Registered email available', 'Step Action': '', 'Step Expected': '' },
  { 'Suite': '', 'Title': '', 'Objective': '', 'Preconditions': '', 'Step Action': 'Click "Forgot password" and submit email', 'Step Expected': 'Confirmation message shown' },
]
const TEMPLATE_NOTES = [
  ['Pathways.io import template — how to fill it in'],
  [''],
  ['1. A row with a value in "Title" starts a NEW test case. Suite / Objective / Preconditions are read from that row.'],
  ['2. Rows below it with an EMPTY Title and a "Step Action" become that case\'s test steps, in order.'],
  ['3. "Suite" is optional — cases with the same suite name are grouped into that suite (created if it does not exist).'],
  ['4. Save as .xlsx or .csv and load it through Test Management → ⇪ Import (preset: Generic or Auto-detect).'],
]

export const exportTemplateXLSX = () => {
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(TEMPLATE_NOTES), 'READ ME')
  const ws = XLSX.utils.json_to_sheet(TEMPLATE_ROWS)
  ws['!cols'] = [{ wch: 22 }, { wch: 30 }, { wch: 36 }, { wch: 28 }, { wch: 40 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, ws, 'Test Cases')
  const out = XLSX.write(wb, { type: 'array', bookType: 'xlsx' })
  download(new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'flowtest-import-template.xlsx')
}

export const exportTemplateCSV = () => {
  const ws = XLSX.utils.json_to_sheet(TEMPLATE_ROWS)
  download(new Blob([XLSX.utils.sheet_to_csv(ws)], { type: 'text/csv' }), 'flowtest-import-template.csv')
}

export const exportTemplateJSON = () => {
  const sample = [
    { suite: 'Checkout Regression', name: 'Login with valid credentials', objective: 'Verify a registered user can sign in', preconditions: 'User account exists',
      steps: [ { action: 'Navigate to login page', expected: 'Login form is displayed' }, { action: 'Enter valid credentials and submit', expected: 'User lands on dashboard' } ] },
    { suite: 'Checkout Regression', name: 'Password reset flow', objective: 'Verify reset email is sent', preconditions: 'Registered email available',
      steps: [ { action: 'Click "Forgot password" and submit email', expected: 'Confirmation message shown' } ] },
  ]
  download(new Blob([JSON.stringify(sample, null, 2)], { type: 'application/json' }), 'flowtest-import-template.json')
}
